import type { LlmConfig } from '@config/index';

export function testLlmConfig(overrides: Partial<LlmConfig> = {}): LlmConfig {
  return {
    primaryProvider: 'gemini',
    fallbackProviders: [],
    defaultModel: 'gemini-3.5-flash',
    fastModel: 'gemini-3.5-flash',
    fallbackModel: 'gpt-4o-mini',
    temperatureDefault: 0,
    maxOutputTokensDefault: 2048,
    maxOutputTokensCeiling: 8192,
    maxInputTokens: 1000,
    inputCharsPerToken: 2.5,
    thinkingBudget: 0,
    requestTimeoutMs: 45_000,
    deadlineMs: 90_000,
    maxAttempts: 4,
    retryBaseMs: 500,
    retryMaxMs: 8000,
    keyCooldownBaseMs: 30_000,
    keyCooldownMaxMs: 1_800_000,
    keyQuotaCooldownMs: 21_600_000,
    keyFailureThreshold: 3,
    keySuccessResetCount: 3,
    cacheDriver: 'memory',
    cacheEnabled: true,
    cacheTtlSeconds: 86_400,
    cacheMaxTemperature: 0.2,
    cacheVersion: 'v1',
    cacheLockTtlMs: 15_000,
    budgetEnforce: true,
    dailyBudgetUsd: 1,
    userDailyBudgetUsd: 0.5,
    userDailyCallLimit: 10,
    callLogEnabled: false,
    callLogTtlDays: 90,
    ...overrides,
  };
}
